# Usamos la imagen base de Ubuntu
FROM ubuntu:latest

# Instalamos JDK 21
RUN apt-get update && \
    apt-get install -y openjdk-21-jdk && \
    apt-get clean;

# Establecemos las variables de entorno para JDK
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

# Verificamos que la instalación de Java fue exitosa
CMD ["java", "-version"]

