# Usa una imagen base de Ubuntu
FROM ubuntu:latest

# Instalar dependencias y OpenJDK
RUN apt-get update && apt-get install -y wget openjdk-21-jdk

# Configurar la ruta de Maven (en este caso en /opt)
RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz \
    && tar -xzvf apache-maven-3.9.6-bin.tar.gz -C /opt \
    && ln -s /opt/apache-maven-3.9.6 /opt/maven

# Establecer las variables de entorno
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV MAVEN_HOME=/opt/maven
ENV PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH

# Verificar que Maven y Java están instalados correctamente
RUN java -version && mvn -v


